title: My First Page
author: John
email: zluckyhou@163.com
description: > # this means to ignore newlines until "baseurl:"
  Hello,You! Welcome to my Blog. Let's take a look and find some interesting storys.

# social links
twitter_username: John
github_username:  zluckyhou

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
